services:
  db:
   image: mongo
   restart: unless-stopped
   ports:
      - 27017:27017
   env_file:
      - .env
   volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/home/app

volumes:
  mongo-data:
