services:
  db:
   image: mongo
   restart: unless-stopped
   env_file:
      - .env
   volumes:
      - mongo-data:/data/db

  backend:
    build: .
    restart: unless-stopped
    ports:
      - "3000:3000"
    links:
      - db

volumes:
  mongo-data:
